### ISSUE TITLE
Trabalhando com Serviços

### ISSUE THREAD

**Issue by walmir41** [walmir41/walmir41.github.io#9]
- [x] Criar docker-compose.yml de configuração
- [x] Iniciar um Nó de cluster para o serviço
- [x] Ativar o serviço (rodar)
- [x] Escalar a aplicação

**Comment by walmir41** [comment]
> * [x]  Criar docker-compose.yml de configuração
```
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: walmirsoares/get-started:part2
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
```
> * [x]  Iniciar um Nó de cluster para o serviço
`docker swarm init`

> * [x]  Ativar o serviço (rodar)
`docker stack deploy -c docker-compose.yml getstartedlab`
`docker service ls    //Listar os serviços`
`docker service ps getstartedlab_web    // Listar as tarefas (processos) ativas do serviço`

> * [x]  Escalar a aplicação
`
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: walmirsoares/get-started:part2
    deploy:
      replicas: 10   //ESCALAR  de 5 para 10. Depois reativar o serviço
`
`docker stack deploy -c docker-compose.yml getstartedlab`

- [x] Retirar a aplicação do Nó
`docker stack rm getstartedlab`

- [x] Retirar o Nó
`docker swarm leave --force`
